#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use JasperPHP\JasperPHPCommand;

$application = new Application('PHPJasper', '1.0');
$application->add(new JasperPHPCommand());
$application->run();
